version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

exclude_patterns:
- "examples/"
- "tests/"
- "docs/"
- "mla/threeml/IceCubeLike.py"

plugins:
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
